# Generated by Django 6.0.8 on 2026-08-14 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openrouter_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('context_length', models.IntegerField(db_index=True, default=0)),
                ('max_completion_tokens', models.IntegerField(blank=True, null=True)),
                ('created_at_openrouter', models.DateTimeField(blank=True, null=True)),
                ('modality', models.CharField(blank=True, default='', max_length=100)),
                ('tokenizer', models.CharField(blank=True, default='', max_length=100)),
                ('instruct_type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_multimodal', models.BooleanField(db_index=True, default=False)),
                ('supports_vision', models.BooleanField(db_index=True, default=False)),
                ('supports_audio', models.BooleanField(db_index=True, default=False)),
                ('supports_tools', models.BooleanField(db_index=True, default=False)),
                ('supports_json_schema', models.BooleanField(default=False)),
                ('prompt_price_per_token', models.DecimalField(decimal_places=12, default=0.0, max_digits=20)),
                ('completion_price_per_token', models.DecimalField(decimal_places=12, default=0.0, max_digits=20)),
                ('image_price', models.DecimalField(decimal_places=12, default=0.0, max_digits=20)),
                ('request_price', models.DecimalField(decimal_places=12, default=0.0, max_digits=20)),
                ('prompt_price_per_1m', models.DecimalField(db_index=True, decimal_places=6, default=0.0, max_digits=14)),
                ('completion_price_per_1m', models.DecimalField(db_index=True, decimal_places=6, default=0.0, max_digits=14)),
                ('is_free', models.BooleanField(db_index=True, default=False)),
                ('elo_score', models.FloatField(db_index=True, default=0.0)),
                ('mmlu_score', models.FloatField(default=0.0)),
                ('human_eval_score', models.FloatField(default=0.0)),
                ('rank_overall', models.IntegerField(db_index=True, default=0)),
                ('tokens_per_second', models.FloatField(default=0.0)),
                ('time_to_first_token', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-elo_score', 'prompt_price_per_1m', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PricingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_price_per_1m', models.DecimalField(decimal_places=6, max_digits=14)),
                ('completion_price_per_1m', models.DecimalField(decimal_places=6, max_digits=14)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='llms.llmmodel')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='llms.provider'),
        ),
    ]
