# Generated by Django 6.0.8 on 2026-08-14 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.BigIntegerField(unique=True)),
                ('app_name', models.CharField(max_length=255)),
                ('rank', models.IntegerField(db_index=True)),
                ('total_tokens', models.BigIntegerField(default=0)),
                ('total_requests', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='TaskClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('macro_category', models.CharField(blank=True, default='', max_length=100)),
                ('usage_share', models.FloatField(default=0.0)),
                ('token_share', models.FloatField(default=0.0)),
                ('top_models_share', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-token_share'],
            },
        ),
        migrations.AlterModelOptions(
            name='llmmodel',
            options={'ordering': ['-intelligence_index', '-elo_score', 'prompt_price_per_1m', 'name']},
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='agentic_index',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='category',
            field=models.CharField(choices=[('llm', 'Language Model'), ('image', 'Image Generation'), ('video', 'Video Generation'), ('embedding', 'Embedding Model')], db_index=True, default='llm', max_length=50),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='coding_index',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='intelligence_index',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.CreateModel(
            name='DailyModelRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_tokens', models.BigIntegerField(default=0)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_rankings', to='llms.llmmodel')),
            ],
            options={
                'ordering': ['-date', '-total_tokens'],
                'unique_together': {('model', 'date')},
            },
        ),
    ]
