# Generated by Django 6.0.8 on 2026-08-14 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llms', '0002_appranking_taskclassification_alter_llmmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='llmmodel',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='llmmodel',
            name='agentic_index',
        ),
        migrations.RemoveField(
            model_name='llmmodel',
            name='coding_index',
        ),
        migrations.RemoveField(
            model_name='llmmodel',
            name='completion_price_per_1m',
        ),
        migrations.RemoveField(
            model_name='llmmodel',
            name='completion_price_per_token',
        ),
        migrations.RemoveField(
            model_name='llmmodel',
            name='context_length',
        ),
        migrations.RemoveField(
            model_name='llmmodel',
            name='elo_score',
        ),
        migrations.RemoveField(
            model_name='llmmodel',
            name='human_eval_score',
        ),
        migrations.RemoveField(
            model_name='llmmodel',
            name='image_price',
        ),
        migrations.RemoveField(
            model_name='llmmodel',
            name='instruct_type',
        ),
        migrations.RemoveField(
            model_name='llmmodel',
            name='intelligence_index',
        ),
        migrations.RemoveField(
            model_name='llmmodel',
            name='is_multimodal',
        ),
        migrations.RemoveField(
            model_name='llmmodel',
            name='max_completion_tokens',
        ),
        migrations.RemoveField(
            model_name='llmmodel',
            name='mmlu_score',
        ),
        migrations.RemoveField(
            model_name='llmmodel',
            name='modality',
        ),
        migrations.RemoveField(
            model_name='llmmodel',
            name='prompt_price_per_1m',
        ),
        migrations.RemoveField(
            model_name='llmmodel',
            name='prompt_price_per_token',
        ),
        migrations.RemoveField(
            model_name='llmmodel',
            name='rank_overall',
        ),
        migrations.RemoveField(
            model_name='llmmodel',
            name='request_price',
        ),
        migrations.RemoveField(
            model_name='llmmodel',
            name='supports_audio',
        ),
        migrations.RemoveField(
            model_name='llmmodel',
            name='supports_json_schema',
        ),
        migrations.RemoveField(
            model_name='llmmodel',
            name='supports_tools',
        ),
        migrations.RemoveField(
            model_name='llmmodel',
            name='supports_vision',
        ),
        migrations.RemoveField(
            model_name='llmmodel',
            name='time_to_first_token',
        ),
        migrations.RemoveField(
            model_name='llmmodel',
            name='tokenizer',
        ),
        migrations.RemoveField(
            model_name='llmmodel',
            name='tokens_per_second',
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='is_open_weight',
            field=models.BooleanField(db_index=True, default=False, help_text='True for open-source/open-weight models (Llama, DeepSeek, Qwen)'),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='license',
            field=models.CharField(blank=True, default='Proprietary', help_text='License type (e.g. MIT, Apache 2.0, Llama 3.3, Proprietary)', max_length=100),
        ),
        migrations.CreateModel(
            name='ModelBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intelligence_index', models.FloatField(db_index=True, default=0.0)),
                ('coding_index', models.FloatField(db_index=True, default=0.0)),
                ('agentic_index', models.FloatField(db_index=True, default=0.0)),
                ('swe_bench_score', models.FloatField(db_index=True, default=0.0, help_text='SWE-bench Resolved % (Software Engineering)')),
                ('human_eval_score', models.FloatField(default=0.0, help_text='HumanEval %')),
                ('mmlu_score', models.FloatField(default=0.0, help_text='MMLU %')),
                ('arena_elo', models.FloatField(db_index=True, default=0.0, help_text='LMSYS Chatbot Arena ELO')),
                ('tokens_per_second', models.FloatField(default=0.0, help_text='Throughput (TPS)')),
                ('time_to_first_token', models.FloatField(default=0.0, help_text='TTFT Latency (seconds)')),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='benchmark', to='llms.llmmodel')),
            ],
            options={
                'ordering': ['-intelligence_index', '-coding_index', '-swe_bench_score', '-arena_elo'],
            },
        ),
        migrations.CreateModel(
            name='ModelPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_price_per_token', models.DecimalField(decimal_places=12, default=0.0, max_digits=20)),
                ('completion_price_per_token', models.DecimalField(decimal_places=12, default=0.0, max_digits=20)),
                ('image_price', models.DecimalField(decimal_places=12, default=0.0, max_digits=20)),
                ('request_price', models.DecimalField(decimal_places=12, default=0.0, max_digits=20)),
                ('prompt_price_per_1m', models.DecimalField(db_index=True, decimal_places=6, default=0.0, max_digits=14)),
                ('completion_price_per_1m', models.DecimalField(db_index=True, decimal_places=6, default=0.0, max_digits=14)),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='llms.llmmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ModelSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_length', models.IntegerField(db_index=True, default=0)),
                ('max_completion_tokens', models.IntegerField(blank=True, null=True)),
                ('modality', models.CharField(blank=True, default='', max_length=100)),
                ('tokenizer', models.CharField(blank=True, default='', max_length=100)),
                ('instruct_type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_multimodal', models.BooleanField(db_index=True, default=False)),
                ('supports_vision', models.BooleanField(db_index=True, default=False)),
                ('supports_audio', models.BooleanField(db_index=True, default=False)),
                ('supports_tools', models.BooleanField(db_index=True, default=False)),
                ('supports_json_schema', models.BooleanField(default=False)),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spec', to='llms.llmmodel')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyTop10Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(db_index=True)),
                ('year', models.IntegerField(db_index=True)),
                ('category', models.CharField(choices=[('coding', 'Top 10 Coding Models'), ('writing_reasoning', 'Top 10 Writing & Reasoning Models'), ('open_source', 'Top 10 Open Source & Open Weight Models'), ('cost_effective', 'Top 10 Value / Cost-Effective Models'), ('overall', 'Top 10 Overall Best AI Models')], db_index=True, max_length=50)),
                ('rank', models.IntegerField(db_index=True, help_text='Rank 1 to 10')),
                ('highlight_reason', models.TextField(blank=True, default='', help_text='Why this model is ranked here this week')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_rankings', to='llms.llmmodel')),
            ],
            options={
                'ordering': ['year', 'week_number', 'category', 'rank'],
                'unique_together': {('week_number', 'year', 'category', 'rank')},
            },
        ),
    ]
