# Generated by Django 6.0.8 on 2026-08-14 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llms', '0003_alter_llmmodel_options_remove_llmmodel_agentic_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(db_index=True)),
                ('intelligence_index', models.FloatField(default=0.0)),
                ('coding_index', models.FloatField(default=0.0)),
                ('agentic_index', models.FloatField(default=0.0)),
                ('swe_bench_score', models.FloatField(default=0.0)),
                ('human_eval_score', models.FloatField(default=0.0)),
                ('mmlu_score', models.FloatField(default=0.0)),
                ('arena_elo', models.FloatField(default=0.0)),
                ('tokens_per_second', models.FloatField(default=0.0)),
                ('time_to_first_token', models.FloatField(default=0.0)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmark_history', to='llms.llmmodel')),
            ],
            options={
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['captured_at', '-intelligence_index'], name='llms_benchm_capture_03a842_idx')],
                'unique_together': {('model', 'captured_at')},
            },
        ),
    ]
