# Generated by Django 6.0.8 on 2026-08-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llms', '0004_benchmarksnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(help_text='Developer or Application name', max_length=255)),
                ('tier', models.CharField(choices=[('free', 'Free Tier (60 req/min)'), ('pro', 'Pro Tier (1000 req/min)'), ('admin', 'Admin Tier (Unlimited)')], default='free', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('total_requests', models.BigIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
