# Generated by Django 6.0.8 on 2026-08-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llms', '0005_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='AABench',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_slug', models.CharField(db_index=True, max_length=250, unique=True)),
                ('model_name', models.CharField(max_length=255)),
                ('creator_name', models.CharField(db_index=True, max_length=150)),
                ('intelligence_index', models.FloatField(db_index=True, default=0.0)),
                ('coding_index', models.FloatField(db_index=True, default=0.0)),
                ('math_index', models.FloatField(default=0.0)),
                ('mmlu_pro', models.FloatField(blank=True, null=True)),
                ('gpqa', models.FloatField(blank=True, null=True)),
                ('livecodebench', models.FloatField(blank=True, null=True)),
                ('math_500', models.FloatField(blank=True, null=True)),
                ('aime', models.FloatField(blank=True, null=True)),
                ('tau2', models.FloatField(blank=True, null=True)),
                ('terminalbench_hard', models.FloatField(blank=True, null=True)),
                ('tokens_per_second', models.FloatField(db_index=True, default=0.0)),
                ('time_to_first_token', models.FloatField(db_index=True, default=0.0)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'aabanch',
                'ordering': ['-intelligence_index', '-coding_index'],
            },
        ),
        migrations.CreateModel(
            name='AAModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=250, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('creator_name', models.CharField(db_index=True, max_length=150)),
                ('creator_slug', models.CharField(blank=True, default='', max_length=150)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('model_type', models.CharField(blank=True, default='', max_length=100)),
                ('context_window', models.IntegerField(db_index=True, default=0)),
                ('max_output_tokens', models.IntegerField(blank=True, null=True)),
                ('prompt_price_per_1m', models.DecimalField(decimal_places=6, default=0.0, max_digits=14)),
                ('completion_price_per_1m', models.DecimalField(decimal_places=6, default=0.0, max_digits=14)),
                ('modalities', models.JSONField(blank=True, default=list)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'aamodels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ORBench',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_permaslug', models.CharField(db_index=True, max_length=250)),
                ('display_name', models.CharField(max_length=255)),
                ('source', models.CharField(db_index=True, max_length=100)),
                ('benchmark_type', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('accuracy', models.FloatField(blank=True, db_index=True, null=True)),
                ('elo', models.FloatField(blank=True, db_index=True, null=True)),
                ('win_rate', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('arena', models.CharField(blank=True, default='', max_length=100)),
                ('intelligence_index', models.FloatField(blank=True, db_index=True, null=True)),
                ('coding_index', models.FloatField(blank=True, db_index=True, null=True)),
                ('agentic_index', models.FloatField(blank=True, null=True)),
                ('avg_cost_per_task', models.FloatField(blank=True, null=True)),
                ('total_tasks', models.IntegerField(blank=True, null=True)),
                ('tournament_stats', models.JSONField(blank=True, default=dict)),
                ('pricing', models.JSONField(blank=True, default=dict)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'orbench',
                'ordering': ['-accuracy', '-elo', '-intelligence_index'],
            },
        ),
        migrations.CreateModel(
            name='ORModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openrouter_id', models.CharField(db_index=True, max_length=250, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('canonical_slug', models.CharField(blank=True, default='', max_length=250)),
                ('author', models.CharField(blank=True, default='', max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('context_length', models.IntegerField(db_index=True, default=0)),
                ('prompt_price_per_1m', models.DecimalField(db_index=True, decimal_places=6, default=0.0, max_digits=14)),
                ('completion_price_per_1m', models.DecimalField(db_index=True, decimal_places=6, default=0.0, max_digits=14)),
                ('is_free', models.BooleanField(db_index=True, default=False)),
                ('architecture', models.JSONField(blank=True, default=dict)),
                ('top_provider', models.JSONField(blank=True, default=dict)),
                ('pricing', models.JSONField(blank=True, default=dict)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ormodels',
                'ordering': ['name'],
            },
        ),
    ]
