# Generated by Django 6.0.8 on 2026-08-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llms', '0006_aabench_aamodel_orbench_ormodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aabench',
            name='aime_25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aabench',
            name='hle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aabench',
            name='ifbench',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aabench',
            name='lcr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aabench',
            name='scicode',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aabench',
            name='tau_banking',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aabench',
            name='terminalbench_v2_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aabench',
            name='math_index',
            field=models.FloatField(db_index=True, default=0.0),
        ),
    ]
