# Generated by Django 6.0.8 on 2026-08-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llms', '0007_aabench_aime_25_aabench_hle_aabench_ifbench_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_slug', models.CharField(db_index=True, max_length=250, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('provider', models.CharField(db_index=True, max_length=150)),
                ('author_slug', models.CharField(blank=True, default='', max_length=150)),
                ('openrouter_id', models.CharField(blank=True, db_index=True, default='', max_length=250)),
                ('aa_slug', models.CharField(blank=True, db_index=True, default='', max_length=250)),
                ('description', models.TextField(blank=True, default='')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('is_open_weight', models.BooleanField(db_index=True, default=False)),
                ('is_free', models.BooleanField(db_index=True, default=False)),
                ('rankllms_index', models.FloatField(db_index=True, default=0.0)),
                ('rank_overall', models.IntegerField(db_index=True, default=0)),
                ('rank_coding', models.IntegerField(default=0)),
                ('rank_reasoning', models.IntegerField(default=0)),
                ('rank_value', models.IntegerField(default=0)),
                ('intelligence_index', models.FloatField(db_index=True, default=0.0)),
                ('coding_index', models.FloatField(db_index=True, default=0.0)),
                ('math_index', models.FloatField(db_index=True, default=0.0)),
                ('terminalbench_hard', models.FloatField(blank=True, null=True)),
                ('terminalbench_v2_1', models.FloatField(blank=True, null=True)),
                ('gpqa_diamond', models.FloatField(blank=True, null=True)),
                ('mmlu_pro', models.FloatField(blank=True, null=True)),
                ('hle', models.FloatField(blank=True, null=True)),
                ('livecodebench', models.FloatField(blank=True, null=True)),
                ('scicode', models.FloatField(blank=True, null=True)),
                ('math_500', models.FloatField(blank=True, null=True)),
                ('aime_25', models.FloatField(blank=True, null=True)),
                ('design_arena_elo', models.FloatField(blank=True, null=True)),
                ('design_arena_win_rate', models.FloatField(blank=True, null=True)),
                ('ifbench', models.FloatField(blank=True, null=True)),
                ('lcr', models.FloatField(blank=True, null=True)),
                ('tau2', models.FloatField(blank=True, null=True)),
                ('tau_banking', models.FloatField(blank=True, null=True)),
                ('context_length', models.IntegerField(db_index=True, default=0)),
                ('max_output_tokens', models.IntegerField(blank=True, null=True)),
                ('prompt_price_per_1m', models.DecimalField(db_index=True, decimal_places=6, default=0.0, max_digits=14)),
                ('completion_price_per_1m', models.DecimalField(db_index=True, decimal_places=6, default=0.0, max_digits=14)),
                ('tokens_per_second', models.FloatField(db_index=True, default=0.0)),
                ('time_to_first_token', models.FloatField(db_index=True, default=0.0)),
                ('has_openrouter', models.BooleanField(default=False)),
                ('has_artificial_analysis', models.BooleanField(default=False)),
                ('has_design_arena', models.BooleanField(default=False)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rankindex',
                'ordering': ['rank_overall', '-rankllms_index', '-intelligence_index'],
            },
        ),
    ]
