# Generated by Django 6.0.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llms', '0008_rankindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelsDevModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelsdev_id', models.CharField(db_index=True, max_length=250, unique=True)),
                ('provider_slug', models.CharField(db_index=True, max_length=150)),
                ('provider_name', models.CharField(blank=True, default='', max_length=150)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('family', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('reasoning', models.BooleanField(db_index=True, default=False)),
                ('tool_call', models.BooleanField(db_index=True, default=False)),
                ('structured_output', models.BooleanField(default=False)),
                ('temperature', models.BooleanField(default=True)),
                ('open_weights', models.BooleanField(db_index=True, default=False)),
                ('release_date', models.DateField(blank=True, db_index=True, null=True)),
                ('last_updated', models.DateField(blank=True, null=True)),
                ('modalities', models.JSONField(blank=True, default=dict)),
                ('context_length', models.IntegerField(db_index=True, default=0)),
                ('max_output_tokens', models.IntegerField(blank=True, null=True)),
                ('prompt_price_per_1m', models.DecimalField(db_index=True, decimal_places=6, default=0.0, max_digits=14)),
                ('completion_price_per_1m', models.DecimalField(decimal_places=6, default=0.0, max_digits=14)),
                ('cache_read_price_per_1m', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=50)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'modelsdev',
                'ordering': ['provider_name', 'name'],
            },
        ),
    ]
