# Generated by Django 6.0.8; additive operational and nullability changes.
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('llms', '0009_modelsdevmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('openrouter', 'OpenRouter'), ('artificial_analysis', 'Artificial Analysis'), ('models_dev', 'models.dev')], max_length=40, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=30)),
                ('retry_count', models.PositiveSmallIntegerField(default=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'ordering': ['source']},
        ),
        migrations.AddField(
            model_name='modelsdevmodel',
            name='canonical_model_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='orbench',
            name='primary_score',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='orbench',
            name='primary_metric',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='orbench',
            name='source_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='orbench',
            name='last_run_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ormodel',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='ormodel',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orbench',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='orbench',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aamodel',
            name='source_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='aamodel',
            name='source_slug',
            field=models.CharField(blank=True, db_index=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='aamodel',
            name='source_endpoint',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='aamodel',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aamodel',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='aabench',
            name='source_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='aabench',
            name='source_slug',
            field=models.CharField(blank=True, db_index=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='aabench',
            name='source_endpoint',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='aabench',
            name='elo',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='aabench',
            name='confidence_interval',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aabench',
            name='samples',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aabench',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='aabench',
            name='price_unit',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='aabench',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aabench',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='modelsdevmodel',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelsdevmodel',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='rankindex',
            name='aliases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rankindex',
            name='category',
            field=models.CharField(blank=True, db_index=True, default='llm', max_length=40),
        ),
        migrations.AddField(
            model_name='rankindex',
            name='family',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='rankindex',
            name='input_modalities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rankindex',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rankindex',
            name='license',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='rankindex',
            name='modelsdev_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='rankindex',
            name='output_modalities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rankindex',
            name='media_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='rankindex',
            name='reasoning',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rankindex',
            name='status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='rankindex',
            name='structured_output',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rankindex',
            name='tool_call',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rankindex',
            name='version',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='category',
            field=models.CharField(choices=[('llm', 'Language Model'), ('image', 'Image Generation'), ('video', 'Video Generation'), ('audio', 'Audio Model'), ('embedding', 'Embedding Model')], db_index=True, default='llm', max_length=50),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='is_free',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='is_open_weight',
            field=models.BooleanField(blank=True, db_index=True, help_text='Whether a source confirms public model weights', null=True),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='license',
            field=models.CharField(blank=True, default='', help_text='License reported by a source, if known', max_length=100),
        ),
        migrations.AlterField(
            model_name='modelbenchmark',
            name='agentic_index',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelbenchmark',
            name='arena_elo',
            field=models.FloatField(blank=True, db_index=True, help_text='LMSYS Chatbot Arena ELO', null=True),
        ),
        migrations.AlterField(
            model_name='modelbenchmark',
            name='coding_index',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelbenchmark',
            name='human_eval_score',
            field=models.FloatField(blank=True, help_text='HumanEval %', null=True),
        ),
        migrations.AlterField(
            model_name='modelbenchmark',
            name='intelligence_index',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelbenchmark',
            name='mmlu_score',
            field=models.FloatField(blank=True, help_text='MMLU %', null=True),
        ),
        migrations.AlterField(
            model_name='modelbenchmark',
            name='swe_bench_score',
            field=models.FloatField(blank=True, db_index=True, help_text='SWE-bench Resolved % (Software Engineering)', null=True),
        ),
        migrations.AlterField(
            model_name='modelbenchmark',
            name='time_to_first_token',
            field=models.FloatField(blank=True, help_text='TTFT Latency (seconds)', null=True),
        ),
        migrations.AlterField(
            model_name='modelbenchmark',
            name='tokens_per_second',
            field=models.FloatField(blank=True, help_text='Throughput (TPS)', null=True),
        ),
        migrations.AlterField(
            model_name='modelpricing',
            name='completion_price_per_1m',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='modelpricing',
            name='completion_price_per_token',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='modelpricing',
            name='image_price',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='modelpricing',
            name='prompt_price_per_1m',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='modelpricing',
            name='prompt_price_per_token',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='modelpricing',
            name='request_price',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='modelsdevmodel',
            name='completion_price_per_1m',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='modelsdevmodel',
            name='context_length',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelsdevmodel',
            name='prompt_price_per_1m',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='modelspecification',
            name='context_length',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelspecification',
            name='is_multimodal',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelspecification',
            name='supports_audio',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelspecification',
            name='supports_json_schema',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelspecification',
            name='supports_tools',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelspecification',
            name='supports_vision',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankindex',
            name='coding_index',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankindex',
            name='completion_price_per_1m',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='rankindex',
            name='context_length',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankindex',
            name='intelligence_index',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankindex',
            name='is_free',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankindex',
            name='is_open_weight',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankindex',
            name='math_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankindex',
            name='prompt_price_per_1m',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='rankindex',
            name='rank_coding',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankindex',
            name='rank_overall',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankindex',
            name='rank_reasoning',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankindex',
            name='rank_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankindex',
            name='rankllms_index',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankindex',
            name='time_to_first_token',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankindex',
            name='tokens_per_second',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='aabench',
            name='coding_index',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='aabench',
            name='intelligence_index',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='aabench',
            name='math_index',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='aabench',
            name='time_to_first_token',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='aabench',
            name='tokens_per_second',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='aamodel',
            name='completion_price_per_1m',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='aamodel',
            name='context_window',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='aamodel',
            name='prompt_price_per_1m',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='modelsdevmodel',
            name='open_weights',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelsdevmodel',
            name='reasoning',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelsdevmodel',
            name='structured_output',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelsdevmodel',
            name='temperature',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelsdevmodel',
            name='tool_call',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='ormodel',
            name='completion_price_per_1m',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='ormodel',
            name='context_length',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='ormodel',
            name='is_free',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='ormodel',
            name='prompt_price_per_1m',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=14, null=True),
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('openrouter', 'OpenRouter'), ('artificial_analysis', 'Artificial Analysis'), ('models_dev', 'models.dev'), ('all', 'All sources')], db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partial'), ('failed', 'Failed'), ('dry_run', 'Dry run')], db_index=True, default='queued', max_length=20)),
                ('dry_run', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('records_received', models.PositiveIntegerField(default=0)),
                ('records_added', models.PositiveIntegerField(default=0)),
                ('records_updated', models.PositiveIntegerField(default=0)),
                ('records_skipped', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('error_summary', models.TextField(blank=True, default='')),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('active_key', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rankllms_sync_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['source', '-started_at'], name='llms_syncru_source_5d2081_idx')],
            },
        ),
    ]
