# Generated by Django 6.1.2 on 2026-10-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llms', '0010_data_sync_and_canonical_provenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='aabench',
            name='agentic_index',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='aabench',
            name='economics_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aabench',
            name='end_to_end_response_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aabench',
            name='engineering_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aabench',
            name='finance_and_accounting_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aabench',
            name='healthcare_and_medical_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aabench',
            name='legal_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aabench',
            name='strategy_and_ops_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aabench',
            name='time_to_first_answer_token',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rankindex',
            name='agentic_index',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='rankindex',
            name='economics_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rankindex',
            name='end_to_end_response_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rankindex',
            name='engineering_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rankindex',
            name='finance_and_accounting_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rankindex',
            name='healthcare_and_medical_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rankindex',
            name='legal_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rankindex',
            name='strategy_and_ops_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rankindex',
            name='time_to_first_answer_token',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
