# Generated by Django 6.1.2 on 2026-10-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llms', '0011_aabench_agentic_index_aabench_economics_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aamodel',
            name='cache_hit_price_per_1m',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='aamodel',
            name='cache_write_price_per_1m',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='rankindex',
            name='aa_cache_hit_price_per_1m',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='rankindex',
            name='aa_cache_write_price_per_1m',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True),
        ),
    ]
