"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-default-key-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').strip().lower() in ('true', '1', 't', 'yes', 'on')

_default_allowed_hosts = (
    'localhost,127.0.0.1,::1,api.rankllms.com,'
    'rankllms-engine-kqso.onrender.com,rankllms-engine.onrender.com'
)
ALLOWED_HOSTS = [
    host.strip().lower()
    for host in os.getenv('ALLOWED_HOSTS', _default_allowed_hosts).split(',')
    if host.strip()
]
if not ALLOWED_HOSTS or '*' in ALLOWED_HOSTS:
    raise ImproperlyConfigured(
        'ALLOWED_HOSTS must contain explicit hostnames; wildcard hosts are not supported.'
    )

# --- HTTPS / proxy-aware security -----------------------------------------
# Render/Cloudflare terminate TLS in front of Gunicorn and forward the
# protocol. Host validation still uses the validated Host header; we do not
# trust X-Forwarded-Host because the app does not need it.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = False

# A production deploy without a real SECRET_KEY falls back to Django's
# well-known default, which would let anyone forge sessions. An empty
# SECRET_KEY= in .env is equally bad, so reject both. Fail loudly instead of
# starting in a compromised state.
if not DEBUG and (not SECRET_KEY or SECRET_KEY == 'django-insecure-default-key-change-me'):
    raise RuntimeError(
        'SECRET_KEY is unset or still the Django default. Generate one with: '
        'python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key)"'
    )

# Secure cookies and HSTS only make sense behind TLS. Keep them off in DEBUG so
# local http://127.0.0.1 development still works.
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True').lower() in ('true', '1', 't')
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party apps
    'corsheaders',
    # Local apps
    'llms.apps.LlmsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise directly after SecurityMiddleware, per its docs. It serves
    # /static/ when DEBUG=False, so the admin UI's CSS/JS loads without nginx.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=True
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise serves collected static files straight from gunicorn, so a
# container deploy needs no nginx `location /static/` block. Storage is
# compressed at collect time and served with immutable caching, since
# collectstatic fingerprints every filename.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# CORS is limited to the product site, the API site, and local development.
# Operators can add a known frontend origin with CORS_ALLOWED_ORIGINS.
_default_cors_origins = (
    'https://rankllms.com,https://www.rankllms.com,https://api.rankllms.com,'
    'http://localhost:3000,http://127.0.0.1:3000'
)
CORS_ALLOWED_ORIGINS = [
    origin.strip().rstrip('/')
    for origin in os.getenv('CORS_ALLOWED_ORIGINS', _default_cors_origins).split(',')
    if origin.strip()
]
CORS_URLS_REGEX = r'^/api/.*$'
CSRF_TRUSTED_ORIGINS = [
    origin.strip().rstrip('/')
    for origin in os.getenv(
        'CSRF_TRUSTED_ORIGINS',
        'https://api.rankllms.com,https://rankllms-engine-kqso.onrender.com',
    ).split(',')
    if origin.strip()
]

ENABLE_SCHEDULER = os.getenv('ENABLE_SCHEDULER', '').strip().lower() in ('1', 'true', 'yes', 'on')
try:
    SYNC_INTERVAL_HOURS = int(os.getenv('SYNC_INTERVAL_HOURS', '6'))
except ValueError as exc:
    raise ImproperlyConfigured('SYNC_INTERVAL_HOURS must be a whole number from 1 to 168.') from exc
if not 1 <= SYNC_INTERVAL_HOURS <= 168:
    raise ImproperlyConfigured('SYNC_INTERVAL_HOURS must be a whole number from 1 to 168.')

# OpenRouter Settings
OPENROUTER_API_URL = os.getenv('OPENROUTER_API_URL', 'https://openrouter.ai/api/v1/models')
OPENROUTER_API_KEY = os.getenv('OPENROUTER_API_KEY', '')

# Artificial Analysis Settings
ARTIFICIAL_ANALYSIS_API_URL = os.getenv('ARTIFICIAL_ANALYSIS_API_URL', 'https://artificialanalysis.ai/api/v2')
ARTIFICIAL_ANALYSIS_API_KEY = os.getenv('ARTIFICIAL_ANALYSIS_API_KEY', '')
ARTIFICIAL_ANALYSIS_MODELS_PATH = os.getenv('ARTIFICIAL_ANALYSIS_MODELS_PATH', 'language/models/free')

# models.dev Settings (provider + model metadata catalog)
MODELS_DEV_API_URL = os.getenv('MODELS_DEV_API_URL', 'https://models.dev/api.json')

